[flavor]
dark  = "catppuccin-mocha"
light = "catppuccin-mocha"

[filetype]
rules = [
	{ mime = "image/*", fg = "#94e2d5" },
	{ mime = "{audio,video}/*", fg = "#f9e2af" },
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },
	{ mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },
	{ mime = "vfs/{absent,stale}", fg = "#9399b2" },
	{ url = "*", fg = "#cdd6f4" },
	{ url = "*/", fg = "#89b4fa", bold = true },
]

