#!/bin/zsh

if [[ "$OSTYPE" == "linux-gnu"* ]]; then

    apt -y --no-install-recommends install fzf stow pydf tilde git-core vim net-tools dnsutils imagemagick mc zsh htop wget curl stow tmux bat coreutils fasd ffmpeg jq lynx nano peco shellcheck tree thefuck fd-find build-essential pandoc html2text &&\
    apt autoremove -qq

    [ ! -d ~/.oh-my-zsh/ ] && sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    [ -f ~/.bin/fd ] && ln -s $(which fdfind) ~/.bin/fd
    [ -f ~/.bin/bat ] && ln -s $(which batcat) ~/.bin/bat

    [ ! -d ~/.bin ] && mkdir ~/.bin

    mv -f ~/.zshrc ~/.zshrc.bak
    ~/.dotfiles/reload

    vim -c ":PluginInstall" -c ":qall"

    [ ! -d ~/.vim/bundle/Vundle.vim ] && git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

    tmux start-server && \
    tmux new-session -d && \
    sleep 1 && \
    ~/.tmux/plugins/tpm/scripts/install_plugins.sh && \
    tmux kill-server

elif [[ "$OSTYPE" == "darwin"* ]]; then

    brew bundle --file=~/.dotfiles/install/brew/Brewfile || true

else
    echo 'Unknown OS!'
    exit
fi


[ ! -d ${ZSH_CUSTOM:-~/.config/zsh}/plugins/zjump ] && git clone https://github.com/qoomon/zjump ${ZSH_CUSTOM:-~/.config/zsh}/plugins/zjump
[ ! -d ${ZSH_CUSTOM:-~/.config/zsh}/plugins/zsh-history-search ] && git clone https://github.com/qoomon/zsh-history-search ${ZSH_CUSTOM:-~/.config/zsh}/plugins/zsh-history-search
[ ! -d ${ZSH_CUSTOM:-~/.config/zsh}/plugins/zsh-syntax-highlighting ] && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.config/zsh}/plugins/zsh-syntax-highlighting
[ ! -d ${ZSH_CUSTOM:-~/.config/zsh}/plugins/zsh-autosuggestions ] && git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.config/zsh}/plugins/zsh-autosuggestions
[ ! -d ${ZSH_CUSTOM:-~/.config/zsh}/plugins/zsh-history-substring-search ] && git clone https://github.com/zsh-users/zsh-history-substring-search ${ZSH_CUSTOM:-~/.config/zsh}/plugins/zsh-history-substring-search

#
# TMUX
#
[ ! -d ~/.tmux/plugins/tpm ] && git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

