# iTerm2 Default Color Scheme for Kitty

foreground #c7c7c7
background #14191e

cursor           #fefffe
cursor_text_color #000000

selection_foreground none
selection_background #c1deff

# Black
color0  #14191e
color8  #676767

# Red
color1  #c91b00
color9  #ff6e67

# Green
color2  #00c200
color10 #57e690

# Yellow
color3  #c7c400
color11 #fefb67

# Blue
color4  #2540b7
color12 #6871ff

# Magenta
color5  #c930c7
color13 #ff76ff

# Cyan
color6  #00c5c7
color14 #5ffdff

# White
color7  #c7c7c7
color15 #feffff
