# Window and opacity

allow_remote_control yes
listen_on unix:/tmp/kitty
enabled_layouts splits,stack

remember_window_size  no
initial_window_width  215c
initial_window_height 66c
remember_window_position yes

hide_window_decorations titlebar-and-corners

confirm_os_window_close 0

background_opacity 0.85
dynamic_background_opacity yes
transparent_background_colors red@0.5 #00ff00@0.3

