description="macOS-specific command-line tools and desktop software"
platforms="mac"
deps="must-have archives docker kitty lazygit mc media navigation storage wezterm yazi nvim"
default="on"
probe="command -v fetch >/dev/null && command -v gpg >/dev/null && command -v pkg-config >/dev/null"
